### House Price Prediction Project
1. Problem Definition :
* Goal predict the sales price for each house

2. Feature selection
* Choose feature to prediction
* Need to use "Feature Engineering " to identify Features needed
 
3. SPlitting the data set 
* x : data [feature]
* y : price 

4. Training ML model

In [2]:
# import library
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("train.csv", index_col = "Id")

In [4]:
data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

#### 2. Feature Selections

In [5]:
features = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF","FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

#### 3. Splitting data set in to x and y

In [6]:
x = data[features]
x.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
Id,,,,,,,
1,8450,2003,856,854,2,3,8
2,9600,1976,1262,0,2,3,6
3,11250,2001,920,866,2,3,6
4,9550,1915,961,756,1,3,7
5,14260,2000,1145,1053,2,4,9

In [9]:
y = data["SalePrice"]
y

Id
1       208500
2       181500
3       223500
4       140000
5       250000
         ...
1456    175000
1457    210000
1458    266500
1459    142125
1460    147500
Name: SalePrice, Length: 1460, dtype: int64

x,y --> x_train, y _train, x_valid, y_valid

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(x,y, train_size = 0.8, test_size = 0.2, random_state = 0)

In [14]:
x_train.shape

(1168, 7)

#### 4. Training Machine Learning Model

In [19]:
from sklearn.tree import  DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=1)

In [20]:
# Fit training data into model
dt_model.fit(x_train, y_train)

DecisionTreeRegressor(random_state=1)

In [24]:
y_preds = dt_model.predict(x_valid.head())
y_preds

array([335000., 140200., 119000., 207500., 112000.])

In [25]:
pd.DataFrame({'y': y_valid.head(), "y_preds" : y_preds})

          y   y_preds
Id
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [26]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

rf_model = RandomForestRegressor(random_state= 1)
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=1)

In [31]:
re_val_product = rf_model.predict(x_valid.head())
re_val_product[:5]

array([271690., 155039., 122024., 188915.,  91147.])

In [32]:
y_valid.head()

Id
530    200624
492    133000
460    110000
280    192000
656     88000
Name: SalePrice, dtype: int64

In [35]:
x_valid.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
Id,,,,,,,
530,32668,1957,2515,0,3,4,9
492,9490,1941,958,620,1,3,5
460,7015,1950,979,224,1,3,5
280,10005,1977,1156,866,2,4,8
656,1680,1971,525,567,1,3,6

In [34]:
rf_model.predict([[6969,2021,1000,800,4,5,8]])

c:\Users\admin\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([206158.4])